'use strict';
// Marker-wrapped instruction blocks. Convention adapted from code-recall (MIT):
// a checksummed BEGIN marker plus an END marker delimit the region we own, so an
// installer can rewrite its own block repeatedly without ever touching the user's
// surrounding content. See ATTRIBUTION.md.

const fs = require('fs');
const path = require('path');
const { writeFileAtomic, sha12 } = require('./util');

const BEGIN_PREFIX = '<!-- gotcha-collector v1 (autogenerated; edit via `gotcha install`) checksum:';
const BEGIN_RE = /<!-- gotcha-collector v1 \(autogenerated; edit via `gotcha install`\) checksum:([0-9a-f]{12}) -->/;
const END = '<!-- /gotcha-collector v1 -->';

function render(body) {
  const text = String(body).replace(/\n+$/, '');
  return BEGIN_PREFIX + sha12(text) + ' -->\n' + text + '\n' + END;
}

function find(text) {
  const m = BEGIN_RE.exec(text);
  if (!m) return null;
  const start = m.index;
  const beginEnd = start + m[0].length;
  const endIdx = text.indexOf(END, beginEnd);
  if (endIdx === -1) return null;
  return { start, beginEnd, endIdx, checksum: m[1] };
}

/**
 * Ensure `filePath` contains exactly our block.
 * Returns 'created' | 'appended' | 'rewritten' | 'unchanged'.
 */
function upsert(filePath, body, createPrefix) {
  const section = render(body);
  let existing = null;
  try { existing = fs.readFileSync(filePath, 'utf8'); } catch (e) { existing = null; }

  if (existing === null) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    writeFileAtomic(filePath, (createPrefix || '') + section + '\n');
    return 'created';
  }
  const found = find(existing);
  if (!found) {
    const sep = existing.endsWith('\n') ? '\n' : '\n\n';
    writeFileAtomic(filePath, existing + sep + section + '\n');
    return 'appended';
  }
  const current = existing.slice(found.start, found.endIdx + END.length);
  if (current === section) return 'unchanged';
  writeFileAtomic(filePath, existing.slice(0, found.start) + section + existing.slice(found.endIdx + END.length));
  return 'rewritten';
}

function present(filePath) {
  try { return !!find(fs.readFileSync(filePath, 'utf8')); } catch (e) { return false; }
}

module.exports = { upsert, present, render, find, BEGIN_PREFIX, END };
