'use strict';
// `gotcha digest` -- the one screen a human reads each week.
// Everything else is automatic; this is where the small human-only pile surfaces.

const fs = require('fs');
const path = require('path');
const facts = require('../facts');
const repos = require('../repos');
const table = require('../table');
const state = require('../state');
const gauntlet = require('../gauntlet');
const { writeFileAtomic, today } = require('../util');
const { candidateFiles } = require('./gauntlet-run');

function run(argv, flags) {
  const out = [];
  const p = (s) => out.push(s === undefined ? '' : s);
  const since = new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10);

  p('# Gotcha digest — ' + today());
  p();
  p('Generated by `gotcha digest`. The gauntlet promotes automatically; this page is');
  p('the part that needs you.');
  p();

  // --- disputes: the only thing that truly blocks ---------------------------
  let disputes = [];
  try { disputes = fs.readdirSync(gauntlet.DISPUTED_DIR).filter((f) => /\.yaml$/.test(f)).sort(); } catch (e) { disputes = []; }
  p('## 1. Disputed — needs your arbitration (' + disputes.length + ')');
  p();
  if (!disputes.length) p('Nothing disputed. ');
  for (const d of disputes) {
    const text = fs.readFileSync(path.join(gauntlet.DISPUTED_DIR, d), 'utf8');
    // Dispute files are written ASCII-escaped (matching facts.yaml style); decode for
    // display, or the digest shows \u2192 where a human expects an arrow.
    const get = (k) => {
      const m = new RegExp('^  ' + k + ': "([\\s\\S]*?)"$', 'm').exec(text);
      if (!m) return '';
      try { return JSON.parse('"' + m[1] + '"'); } catch (e) { return m[1].replace(/\\"/g, '"'); }
    };
    p('- **`' + (get('candidate_id') || d) + '`** — ' + (get('kind') || '?'));
    p('  - claim: ' + get('claim').slice(0, 160));
    p('  - examiner said: ' + get('examiner_evidence').slice(0, 200));
    p('  - decide: ' + get('decide'));
    p('  - file: `disputed/' + d + '`');
  }
  p();

  // --- auto-promoted this week ---------------------------------------------
  const found = table.findFor(path.join(repos.HOME, 'user-dashboard-main'));
  let auto = [];
  let byStatus = {};
  if (found) {
    try {
      const doc = table.loadFound(found);
      for (const f of doc.facts) byStatus[f.status] = (byStatus[f.status] || 0) + 1;
      auto = doc.facts.filter((f) => f.provenance && /auto-gauntlet/.test(f.provenance) && f.verified_at >= since);
    } catch (e) { /* ignore */ }
  }
  p('## 2. Auto-promoted since ' + since + ' (' + auto.length + ')');
  p();
  if (!auto.length) p('None.');
  for (const f of auto) p('- `' + f.id + '` — ' + String(f.claim).replace(/\s+/g, ' ').slice(0, 130));
  p();

  // --- human-asserted queue -------------------------------------------------
  let noCheck = [];
  for (const file of candidateFiles()) {
    try {
      const doc = facts.parse(fs.readFileSync(file, 'utf8'), { strict: false });
      for (const f of doc.facts) {
        if (f.promoted || f.gauntlet) continue;
        if (/^\s*unresolved /.test(String(f.check || ''))) noCheck.push(f);
      }
    } catch (e) { /* skip */ }
  }
  p('## 3. Human-asserted queue (' + noCheck.length + ')');
  p();
  p('No runnable check exists, so no gauntlet can validate these. They are the only');
  p('things that still need a person. Showing the 15 most recent:');
  p();
  for (const f of noCheck.slice(-15)) p('- `' + f.id + '` — ' + String(f.claim).replace(/\s+/g, ' ').slice(0, 130));
  p();

  // --- verify health --------------------------------------------------------
  const st = state.read();
  p('## 4. Verifier');
  p();
  p('- last verify: ' + (st.lastVerifyResult || 'never'));
  p('- last gauntlet: ' + (st.lastGauntletResult || 'never') + (st.lastGauntlet ? ' (' + st.lastGauntlet.slice(0, 16).replace('T', ' ') + ')' : ''));
  p('- table: ' + Object.keys(byStatus).sort().map((k) => byStatus[k] + ' ' + k).join(', '));
  p();

  const dest = path.join(repos.GOTCHA_HOME, 'DIGEST.md');
  writeFileAtomic(dest, out.join('\n') + '\n');
  console.log(dest);
  if (!flags.quiet) {
    console.log('');
    console.log('  disputed ' + disputes.length + '  |  auto-promoted ' + auto.length +
      '  |  human-asserted queue ' + noCheck.length);
  }
  return 0;
}

module.exports = { run };
