'use strict';
// `gotcha impact` -- re-check only the facts a change actually touches.
//
// The weekly sweep answers "is the table still true?" once a week. This answers
// "does THIS change contradict something we know?" at the moment the change is
// proposed, which is when it is cheap to act on.
//
// A pull request run NEVER writes. A contradicted fact on a PR is a claim that would
// become false IF merged -- it is not false yet, and demoting it while the PR might
// be abandoned would put a lie in the table. The write happens on push to the default
// branch, where the change is real.

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const facts = require('../facts');
const checks = require('../checks');
const anchors = require('../anchors');
const repos = require('../repos');
const { writeFileAtomic, today } = require('../util');

const WORKFLOW = `# Re-check stored facts whose evidence this PR touches.
# Generated by \`gotcha impact --github-action\`. Set GOTCHA_REPO/GOTCHA_REF below.
#
# On a pull request this only REPORTS. A contradicted fact is a claim that would
# become false if merged -- it is not false yet, and demoting it from a PR that might
# be abandoned would put a lie in the table. The write happens on push to the default
# branch, via the normal branch+PR flow for facts.yaml.
name: Fact impact

on:
  pull_request:
  push:
    branches: [__DEFAULT_BRANCH__]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: fact-impact-\${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  impact:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GOTCHA_REPO: __GOTCHA_REPO__
      GOTCHA_REF: v1
      FACTS_REPO: __FACTS_REPO__
    steps:
      - name: Check out this repo at the proposed change
        uses: actions/checkout@v4
        with:
          path: clones/\${{ github.event.repository.name }}
          fetch-depth: 0

      # Pinned to a TAG, not main: a collector bug must not be able to break CI in
      # three repos at once. Move the tag deliberately.
      - name: Check out gotcha
        uses: actions/checkout@v4
        with:
          repository: \${{ env.GOTCHA_REPO }}
          ref: \${{ env.GOTCHA_REF }}
          token: \${{ secrets.REPO_TRUTH_READ_TOKEN }}
          path: gotcha

      # Facts live in user-dashboard. Sibling clones let cross-repo checks resolve.
      - name: Fetch the fact table and sibling clones
        env:
          READ_TOKEN: \${{ secrets.REPO_TRUTH_READ_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          auth=$(printf 'x-access-token:%s' "$READ_TOKEN" | base64 | tr -d '\\n')
          echo "::add-mask::$auth"
          for repo in __REPO_LIST__; do
            [ -d "clones/$repo" ] && continue
            git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic $auth" \\
              clone --quiet --depth 1 "https://github.com/__OWNER__/$repo.git" "clones/$repo"
          done

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Which facts does this change touch?
        id: impact
        shell: bash
        run: |
          set -euo pipefail
          if [ "\${{ github.event_name }}" = "pull_request" ]; then
            base="\${{ github.event.pull_request.base.sha }}"
            changed=$(git -C "clones/\${{ github.event.repository.name }}" diff --name-only "$base" HEAD | tr '\\n' ',')
          else
            changed=$(git -C "clones/\${{ github.event.repository.name }}" diff --name-only HEAD~1 HEAD | tr '\\n' ',')
          fi
          # A contradiction makes gotcha exit non-zero. That is the POINT, but it must
          # not abort this step -- the comment is the whole deliverable, and under
          # set -e an aborted step means the comment never posts. Capture the code,
          # always emit the outputs, and decide the job's verdict after commenting.
          rc=0
          node gotcha/bin/gotcha impact \\
            --repo-name "\${{ github.event.repository.name }}" \\
            --facts "clones/__FACTS_DIR__/repo-truth/facts.yaml" \\
            --root clones \\
            --changed "$changed" \\
            --comment-file impact-comment.md || rc=$?
          echo "has_comment=$([ -s impact-comment.md ] && echo yes || echo no)" >> "$GITHUB_OUTPUT"
          echo "contradicted=$rc" >> "$GITHUB_OUTPUT"

      - name: Comment on the pull request
        if: github.event_name == 'pull_request' && steps.impact.outputs.has_comment == 'yes'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('impact-comment.md', 'utf8');
            const marker = '<!-- gotcha-fact-impact -->';
            const { data: comments } = await github.rest.issues.listComments({
              ...context.repo, issue_number: context.issue.number, per_page: 100,
            });
            const mine = comments.find((c) => c.body && c.body.includes(marker));
            if (mine) {
              await github.rest.issues.updateComment({ ...context.repo, comment_id: mine.id, body });
            } else {
              await github.rest.issues.createComment({ ...context.repo, issue_number: context.issue.number, body });
            }

      # Verdict last, so a contradiction shows as a red check AND a comment that
      # says which claim it contradicted.
      - name: Fail if this change contradicts a stored fact
        if: steps.impact.outputs.contradicted != '0'
        shell: bash
        run: |
          echo "This change contradicts at least one stored fact — see the PR comment."
          exit 1
`;

function classify(list, ctx) {
  const contradicted = [];
  const needsRecheck = [];
  const stillPass = [];
  for (const { fact, hits } of list) {
    const missing = anchors.missingAnchors(fact, ctx.root, fs, path);
    if (missing.length) {
      needsRecheck.push({ fact, hits, missing });
      continue;
    }
    const r = checks.runCheck(fact.check, { root: ctx.root, here: ctx.here });
    if (r.rc === 0) stillPass.push({ fact, hits });
    else if (fact.status === 'failed') stillPass.push({ fact, hits, known: true });
    else contradicted.push({ fact, hits, output: r.output });
  }
  return { contradicted, needsRecheck, stillPass };
}

function comment(res, repoName, changedCount) {
  const n = res.contradicted.length + res.needsRecheck.length + res.stillPass.length;
  const out = ['<!-- gotcha-fact-impact -->'];
  out.push('This PR touches evidence for **' + n + '** stored fact' + (n === 1 ? '' : 's') + ': ' +
    '**' + res.stillPass.length + '** still pass, **' + res.contradicted.length + '** now FAIL.');
  out.push('');
  if (res.contradicted.length) {
    out.push('### Contradicted — this change makes ' + res.contradicted.length + ' recorded claim' +
      (res.contradicted.length === 1 ? '' : 's') + ' false');
    out.push('');
    for (const c of res.contradicted) {
      out.push('- **`' + c.fact.id + '`** (`' + c.fact.status + '`, verified ' + c.fact.verified_at + ')');
      out.push('  > ' + String(c.fact.claim).replace(/\s+/g, ' ').slice(0, 220));
      out.push('  - anchor touched: ' + c.hits.map((h) => '`' + h + '`').join(', '));
      if (c.output) out.push('  - check now says: `' + String(c.output).split('\n')[0].slice(0, 160) + '`');
    }
    out.push('');
    out.push('Nothing was written. If this PR merges, the same step runs on the default');
    out.push('branch and opens a PR demoting these to `failed`. If the claim should still');
    out.push('hold, this is a bug in the change rather than a stale fact.');
    out.push('');
  }
  if (res.needsRecheck.length) {
    out.push('### Needs recheck — anchor moved or deleted, so the check cannot run');
    out.push('');
    for (const c of res.needsRecheck) {
      out.push('- **`' + c.fact.id + '`** — missing: ' + c.missing.map((m) => '`' + m + '`').join(', '));
      out.push('  > ' + String(c.fact.claim).replace(/\s+/g, ' ').slice(0, 180));
    }
    out.push('');
    out.push('These are not contradicted, just un-checkable here. Re-anchor the fact or');
    out.push('confirm the evidence moved.');
    out.push('');
  }
  if (res.stillPass.length) {
    out.push('<details><summary>' + res.stillPass.length + ' touched fact' +
      (res.stillPass.length === 1 ? '' : 's') + ' still pass</summary>');
    out.push('');
    for (const c of res.stillPass) out.push('- `' + c.fact.id + '`' + (c.known ? ' (already recorded `failed`)' : ''));
    out.push('');
    out.push('</details>');
    out.push('');
  }
  out.push('<sub>' + changedCount + ' changed file(s) in `' + repoName +
    '` · facts anchor to files, so only the intersecting checks ran.</sub>');
  return out.join('\n');
}

function repoList(cfg) {
  const names = (cfg.repos || []).map((r) => path.basename(repos.expand(r)));
  return names.length ? names.join(' ') : '<repo>';
}
function factsRepoSlug(cfg) {
  const owner = cfg.githubOwner || '<owner>';
  const name = cfg.factsRepo ? path.basename(repos.expand(cfg.factsRepo))
    : ((cfg.repos || []).map((r) => path.basename(repos.expand(r)))[0] || '<repo>');
  return owner + '/' + name;
}

function run(argv, flags) {
  const cfg = require('../config').load();
  if (flags['github-action']) {
    const branch = String(flags.branch || 'main');
    process.stdout.write(WORKFLOW
      .replace('__DEFAULT_BRANCH__', branch)
      .replace('__GOTCHA_REPO__', String(flags['gotcha-repo'] || cfg.gotchaRepo || '<owner>/gotcha-collector'))
      .replace('__FACTS_REPO__', String(flags['facts-repo'] || factsRepoSlug(cfg)))
      .replace(/__OWNER__/g, String(flags.owner || cfg.githubOwner || '<owner>'))
      .replace('__REPO_LIST__', repoList(cfg))
      .replace('__FACTS_DIR__', factsRepoSlug(cfg).split('/').pop()));
    return 0;
  }

  const repoName = flags['repo-name'];
  if (!repoName) { console.error('gotcha impact: --repo-name is required'); return 2; }
  const factsPath = path.resolve(repos.expand(String(flags.facts || path.join(repos.HOME, 'user-dashboard-main', 'repo-truth', 'facts.yaml'))));
  if (!fs.existsSync(factsPath)) { console.error('gotcha impact: no fact table at ' + factsPath); return 2; }
  const root = path.resolve(repos.expand(String(flags.root || repos.HOME)));
  const here = path.dirname(factsPath);

  let changed = [];
  if (flags.changed) changed = String(flags.changed).split(',').map((s) => s.trim()).filter(Boolean);
  else if (flags.base) {
    const repoDir = path.join(root, repoName);
    const out = execFileSync('git', ['-C', repoDir, 'diff', '--name-only', String(flags.base), 'HEAD'], { encoding: 'utf8' });
    changed = out.split('\n').filter(Boolean);
  }
  if (!changed.length) { console.log('gotcha impact: no changed files given; nothing to do.'); return 0; }

  const doc = facts.parse(fs.readFileSync(factsPath, 'utf8'), { strict: false });
  const list = anchors.affected(doc.facts, repoName, changed);
  if (!list.length) {
    console.log('gotcha impact: ' + changed.length + ' changed file(s) in ' + repoName +
      ' touch no stored fact evidence.');
    if (flags['comment-file']) { try { fs.unlinkSync(path.resolve(String(flags['comment-file']))); } catch (e) { /* none */ } }
    return 0;
  }

  const res = classify(list, { root, here });
  const body = comment(res, repoName, changed.length);
  console.log('  touched ' + list.length + ' fact(s): ' + res.stillPass.length + ' pass, ' +
    res.contradicted.length + ' contradicted, ' + res.needsRecheck.length + ' needs-recheck');
  for (const c of res.contradicted) console.log('    CONTRADICTED ' + c.fact.id);
  for (const c of res.needsRecheck) console.log('    NEEDS-RECHECK ' + c.fact.id);

  if (flags['comment-file']) {
    writeFileAtomic(path.resolve(String(flags['comment-file'])), body + '\n');
  } else if (!flags.quiet) {
    console.log('');
    console.log(body);
  }

  // Only a default-branch run writes: on main the change is real.
  if (flags.write && res.contradicted.length) {
    const updates = {};
    for (const c of res.contradicted) {
      updates[c.fact.id] = {
        status: 'failed',
        verified_at: today(),
        note: 'Demoted by gotcha impact on ' + today() + ': a change to ' +
          c.hits.join(', ') + ' contradicted this claim. Check output: ' +
          (String(c.output).split('\n')[0] || 'no output') + (c.fact.note ? ' Prior note: ' + c.fact.note : ''),
      };
    }
    const src = fs.readFileSync(factsPath, 'utf8');
    writeFileAtomic(factsPath, facts.applyUpdates(src, updates));
    console.log('  wrote ' + Object.keys(updates).length + ' demotion(s) to ' + factsPath + ' (NOT committed)');
  }
  return res.contradicted.length ? 1 : 0;
}

module.exports = { run, classify, comment, WORKFLOW };
