'use strict';
const fs = require('fs');
const path = require('path');
const facts = require('../facts');
const checks = require('../checks');
const repos = require('../repos');
const { writeFileAtomic, today } = require('../util');
const state = require('../state');
const baselineLib = require('../baseline');

const WORKFLOW_TEMPLATE = `# Weekly re-verification of repo-truth/facts.yaml.
# Generated by \`gotcha verify --github-action\`. Adjust GOTCHA_REF/GOTCHA_REPO below.
#
# Scope note: checks address files as "<repo-name>/<path>", so they resolve against a
# directory CONTAINING the clone. This workflow checks out one repo; cross-repo facts
# need the other clones added here too (see repo-truth/verify.sh's CI workflow).
name: Repo truth

on:
  pull_request:
    paths:
      - 'repo-truth/**'
      - '.github/workflows/repo-truth.yml'
  schedule:
    - cron: '23 12 * * 1'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: repo-truth-\${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GOTCHA_REPO: __GOTCHA_REPO__
      GOTCHA_REF: v1
    steps:
      - name: Check out this repo into a named directory
        uses: actions/checkout@v4
        with:
          path: clones/\${{ github.event.repository.name }}

      - name: Check out gotcha
        uses: actions/checkout@v4
        with:
          repository: \${{ env.GOTCHA_REPO }}
          ref: \${{ env.GOTCHA_REF }}
          token: \${{ secrets.REPO_TRUTH_READ_TOKEN }}
          path: gotcha

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # The baseline carries the PREVIOUS run's per-fact outcome. Without it this job
      # goes green the moment a regression is recorded as \`failed\`, because the
      # verifier treats \`failed\` as already-known. The rolling cache key restores the
      # most recent baseline and saves a fresh one each run.
      - name: Restore fact-outcome baseline
        uses: actions/cache@v4
        with:
          path: .gotcha-baseline.json
          key: gotcha-baseline-\${{ github.run_id }}
          restore-keys: |
            gotcha-baseline-

      - name: Re-verify the fact table
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p results
          # --baseline makes the exit status a DIFF: a regression fails the run once,
          # on the run it appears. Already-known failures stay green.
          node gotcha/bin/gotcha verify \\
            "clones/\${{ github.event.repository.name }}" \\
            --root clones \\
            --baseline .gotcha-baseline.json \\
            --report results/verification.txt

      - name: Preserve the baseline
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gotcha-baseline
          path: .gotcha-baseline.json
          if-no-files-found: warn

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: repo-truth-results
          path: results/verification.txt
          if-no-files-found: error
          retention-days: 30
`;

function run(argv, flags) {
  if (flags['github-action']) {
    const cfg = require('../config').load();
    process.stdout.write(WORKFLOW_TEMPLATE
      .replace('__GOTCHA_REPO__', String(flags['gotcha-repo'] || cfg.gotchaRepo || '<owner>/gotcha-collector')));
    return 0;
  }
  const target = repos.resolve(argv[0] || '.', { root: flags.root });
  // Mirrors verify.sh's REPO_TRUTH_FACTS: point the run at an alternate table
  // (an audit draft, a scratch copy) without moving the repo's real one.
  if (flags.facts) target.factsPath = path.resolve(repos.expand(String(flags.facts)));
  if (!fs.existsSync(target.factsPath)) {
    console.error('gotcha verify: no fact table at ' + target.factsPath);
    const head = repos.git(target.repoPath, ['rev-parse', '--abbrev-ref', 'HEAD']);
    if (head) {
      console.error('  ' + target.name + ' is on branch ' + head + '.');
      console.error('  If repo-truth/ lives on another branch, check it out or pass a path that has it.');
    }
    return 2;
  }

  let doc;
  try {
    doc = facts.load(target.factsPath);
  } catch (e) {
    console.error('SCHEMA-ERROR ' + e.message);
    return 2;
  }

  const lines = [];
  const emit = (s) => { lines.push(s); if (!flags.quiet) console.log(s); };

  // Snapshot every clone under ROOT that any fact's scope names, so the report
  // records exactly which trees the checks were evaluated against.
  const scoped = new Set();
  for (const f of doc.facts) for (const s of f.scope) scoped.add(s);
  for (const name of Array.from(scoped).sort()) {
    const p = path.join(target.root, name);
    if (!repos.isRepo(p)) continue;
    emit('SNAPSHOT ' + name + ' ' + repos.git(p, ['rev-parse', 'HEAD']));
  }

  const counts = { PASS: 0, FAIL: 0, 'KNOWN-FAIL': 0, RECOVERED: 0, 'HUMAN-ASSERTED': 0, 'RUNTIME-NOT-RECHECKED': 0 };
  const outcomes = [];
  const updates = {};
  const newlyDisproven = [];
  const recovered = [];

  for (const fact of doc.facts) {
    const { rc, output } = checks.runCheck(fact.check, { root: target.root, here: target.here });
    const label = checks.label(fact.status, rc);
    counts[label] = (counts[label] || 0) + 1;
    outcomes.push({ id: fact.id, status: fact.status, rc, label });
    emit(label + ' ' + fact.id + ' (check exit ' + rc + ')');
    if (output) emit('  ' + output);

    if (checks.isRegression(fact.status, rc)) {
      newlyDisproven.push({ fact, output });
      if (flags.write) {
        // A verified claim whose check now fails is disproven: demote it so agents
        // reading the table are warned off, and record WHY in the fact itself.
        updates[fact.id] = {
          status: 'failed',
          verified_at: today(),
          note: 'Auto-demoted by gotcha verify on ' + today() + ': check failed. ' +
            (output ? 'Output: ' + output : 'No output.') +
            (fact.note ? ' Prior note: ' + fact.note : ''),
        };
      }
    } else if (label === 'RECOVERED') {
      recovered.push(fact);
    } else if (fact.status === 'verified' && rc === 0 && flags.write && flags.touch) {
      // Opt-in only. Refreshing verified_at on every passing fact is semantically
      // right but rewrites ~75 lines per run, burying the one status change that
      // actually needs review in a diff nobody will read.
      updates[fact.id] = { verified_at: today() };
    }
  }

  const unverifiable = counts['HUMAN-ASSERTED'] + counts['RUNTIME-NOT-RECHECKED'];
  emit('SUMMARY facts=' + doc.facts.length + ' verified_regressions=' + newlyDisproven.length);

  // --- baseline diff (opt-in; absent => behave exactly like verify.sh) -------
  let baselineFailed = false;
  if (flags.baseline) {
    const bPath = path.resolve(repos.expand(String(flags.baseline)));
    const prior = baselineLib.read(bPath);
    const diff = baselineLib.compare(prior, outcomes);
    if (diff.seeded) {
      emit('BASELINE seeded ' + outcomes.length + ' fact outcome(s); no comparison on the first run');
    } else {
      for (const r of diff.regressions) emit('REGRESSION ' + baselineLib.describe(r));
      for (const r of diff.recoveries) emit('IMPROVED ' + baselineLib.describe(r));
      for (const id of diff.dropped) emit('BASELINE-DROPPED ' + id + ' (no longer in the fact table)');
      emit('BASELINE facts=' + outcomes.length + ' regressions_since_baseline=' + diff.regressions.length);
      baselineFailed = diff.regressions.length > 0;
    }
    baselineLib.write(bPath, outcomes);
    if (!flags.quiet && !diff.seeded && diff.regressions.length) {
      console.log('');
      console.log('  ' + diff.regressions.length + ' fact(s) got WORSE than the last run.');
      console.log('  Already-known failures stay green; this is new since the baseline.');
    }
  }

  if (!flags.quiet) {
    console.log('');
    console.log('  passing        ' + counts.PASS);
    console.log('  DISPROVEN NOW  ' + newlyDisproven.length + (newlyDisproven.length ? '  <- a verified claim just failed its check' : ''));
    console.log('  known-failed   ' + counts['KNOWN-FAIL'] + '  (already recorded as disproven)');
    console.log('  recovered      ' + counts.RECOVERED + (counts.RECOVERED ? '  <- was failed, now passes; needs review' : ''));
    console.log('  unverifiable   ' + unverifiable + '  (' + counts['HUMAN-ASSERTED'] + ' human-asserted, ' +
      counts['RUNTIME-NOT-RECHECKED'] + ' runtime) - second-class: no offline proof');
    if (flags.write) {
      console.log('');
      console.log('  wrote ' + Object.keys(updates).length + ' fact update(s) to ' + target.factsPath);
      console.log('  NOT committed - review with: git -C ' + target.repoPath + ' diff -- repo-truth/facts.yaml');
    } else if (newlyDisproven.length || counts.RECOVERED) {
      console.log('');
      console.log('  re-run with --write to record these status changes in facts.yaml');
    }
  }

  if (flags.write && Object.keys(updates).length) {
    const src = fs.readFileSync(target.factsPath, 'utf8');
    writeFileAtomic(target.factsPath, facts.applyUpdates(src, updates));
  }
  state.patch({
    lastVerify: new Date().toISOString(),
    lastVerifyResult: counts.PASS + ' pass, ' + newlyDisproven.length + ' disproven, ' +
      counts['KNOWN-FAIL'] + ' known-failed, ' + unverifiable + ' unverifiable',
  });

  if (flags.report) {
    fs.mkdirSync(path.dirname(path.resolve(flags.report)), { recursive: true });
    writeFileAtomic(path.resolve(flags.report), lines.join('\n') + '\n');
  }
  // In baseline mode the exit status is the DIFF, not the absolute state: a fact that
  // was already failing at the baseline is the acknowledged state, and failing the
  // build on it every week is how a red build stops meaning anything. A regression is
  // loud on the run it appears and quiet thereafter.
  if (flags.baseline) return baselineFailed ? 1 : 0;
  return newlyDisproven.length ? 1 : 0;
}

module.exports = { run, WORKFLOW_TEMPLATE };
